version: '3'

services: 
  backend:
    build: ./backend
    expose: 
      - 5000
    ports: 
      - 5000:5000
    volumes: 
      - ./backend:/app
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
  frontend:
    build: 
      context: ./frontend
      dockerfile: serve.Dockerfile
    expose: 
      - 8080
    ports: 
      - 8080:8080
    volumes: 
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    links: 
      - 'backend'
    